# Generated by Django 3.2.5 on 2021-08-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtfolioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='portfolio/%y')),
                ('img_caption', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('portfolio_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.protfoliotype')),
            ],
        ),
    ]
