# Generated by Django 3.2.5 on 2021-08-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfolio_protfoliotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.protfoliotype'),
        ),
    ]
